### ISSUE TITLE
Em percurso académico, eliminar: discurso de posse; data de posse. E grau > categoria.

### ISSUE THREAD

**Issue by anacastrosalgado** [illlp/DHB#23]

**Comment by celsoclaro** [comment]
Feito.

**Comment by anacastrosalgado** [comment]
A estrutura deve ser a seguinte:
Nas listagens, seria interessante visualizar o artigo, e não apenas editar. Acrescentámos VER, EDITAR e APAGAR.

Percurso (pesquisa inteligente)
Nacionalidade
Data de eleição:
Data de posse: ELIMINAR
Classe:
Secção:
Cadeira:
Antecedido por: –
Sucedido por:
Discurso de posse: ELIMINAR
Elogio histórico:
Grau de entrada: > Categoria
Historial: VALIDADO.
Cargos: ELIMINAR

**Comment by celsoclaro** [comment]
Pseudónimo ainda aparecia no ficheiro base de criação de novo verbete bibliográfico. Já eliminei.
Data de posse e discurso de posse já tinha eliminado.
Grau de entrada passou a Categoria.
Cargos, eliminei.

**Comment by anacastrosalgado** [comment]
OK. Parfait.

**Comment by anacastrosalgado** [comment]
criar Secção em percurso académico (após Classe) https://github.com/illlp/DHB/issues/25

**Comment by anacastrosalgado** [comment]
criar Secção em percurso académico (após Classe) https://github.com/illlp/DHB/issues/25
